<?php $collection = $block->getNewsCollection(); ?>
<?php if($collection->count() > 0): ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
    <table class="data table" id="news-data-table">
        <caption class="table-caption">Addweb News Data</caption>
        <thead>
            <tr>
                <th scope="col" class="col title">Title</th>
                <th scope="col" class="col description">Description</th>
                <th scope="col" class="col image">Image</th>
                <th scope="col" class="col actions">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($collection as $key => $data): ?>
                <tr>
                    <td data-th="Title" class="col title"><?php echo $data->getTitle(); ?></td>
                    <td data-th="Author" class="col description"><?php echo $data->getDescription(); ?></td>
                    <td data-th="Image" class="col image">
                        <?php if($data->getImage()): ?>
                            <img width="70" height="70" src="<?php echo $block->getBaseUrl().'pub/media/'.$data->getImage(); ?>">
                        <?php else: ?>
                            <p>No Image</p>
                        <?php endif; ?>
                    </td>
                    <td data-th="Actions" class="col actions">
                        <?php $id = ($data->getNewsId()) ? $data->getNewsId() : $data['news_id']; ?>
                        <a href="<?php echo $block->getBaseUrl().'news/index/view/news_id/'.$id; ?>" class="action view">
                            <span>View</span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <h2>We couldn't find any records</h2>
<?php endif; ?>